FROM alpine:3.16.2
LABEL maintainer="Maxim Makeev <maximalmax90@mail.ru>"

RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ mono bash curl screen unzip

RUN mkdir /HKMP
RUN mkdir /FILES
RUN LATEST="VERS"; \
    curl -sOL https://github.com/Extremelyd1/HKMP/releases/download/$LATEST/HKMPServer.zip
RUN unzip -o HKMPServer.zip -d /FILES
WORKDIR /HKMP
COPY hkmp_pre /bin/hkmp
COPY run.sh /run.sh

ENTRYPOINT ["/run.sh"]
