#!/bin/bash
SESSION="server"
LOG="logs/server.log"
EXE="HKMPServer.exe"
PDB="HKMPServer.pdb"
DIR="/HKMP"
TMPDIR="/FILES"

execute() {
        STR="${@}"^M
        screen -S server -X stuff "$STR"
        sleep 1;
        tail -n1 ${LOG}
}

help() {
        echo "Usage:"
        echo "All commands sends to server by default. Check the official wiki for a complete list of commands."
        echo "Additional command:"
        echo "exit - stop a server"
}

case "$1" in
        "help"   ) help;;
        *        ) execute ${@};;
esac
